spring.application.name=productjpa


#testing local computer
#server.port=8083

#for railway
server.port=${PORT:8080};

#maria DB setting
#spring.datasource.url=jdbc:mariadb://localhost:3306/productdb
#spring.datasource.username=root
#spring.datasource.password=root1234!


#PostgreSQL DB Setting
#spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
#spring.datasource.username=postgres
#spring.datasource.password=root1234!

#for railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB